project:
  type: website

website:
  title: "DH 140 Final Project"
  navbar:
    left:
      - text: Home
        href: finalproject.ipynb
      - text: About
        href: about.qmd
      - text: Project
        href: finalproject.ipynb

format:
  html:
    theme: default

author: "Abishan Sutharshan"
