title: Your Site Title
description: >- # this means to ignore newlines until "baseurl:"
  Your site description
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://abishan1.github.io/dh140proj" # the base hostname & protocol for your site

markdown: kramdown
theme: minima

# Build settings
plugins:
  - jekyll-feed
