name: Deploy Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions@v2

      - name: Render and Deploy
        run: |
          quarto render
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Deploy site'
          git push --force origin `HEAD:refs/heads/gh-pages`
